Addresses several shellcheck issues

diff --git a/git-credential-bw b/git-credential-bw
--- a/git-credential-bw
+++ b/git-credential-bw
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 log_init() {
-    [[ ! -d "$(dirname ${LOG_FILE})" ]] && mkdir -p "$(dirname ${LOG_FILE})"
+    [[ ! -d "$(dirname "${LOG_FILE}")" ]] && mkdir -p "$(dirname "${LOG_FILE}")"
 
     printf '=%.0s' {1..80} >> "${LOG_FILE}"
     printf "\nScript started at %s\n" "$(date)" >> "${LOG_FILE}"
@@ -22,7 +22,7 @@ get_bw_status() {
 }
 
 get_credentials() {
-    local protocol host username password key value max_attempts attempts
+    local protocol host username key value max_attempts attempts
     max_attempts=3
     attempts=0
     
@@ -61,12 +61,14 @@ get_credentials() {
             unauthenticated)
                 log "ERROR" "Bitwarden CLI is unauthenticated!"
                 echo "Please login to bitwarden." >&2
-                export BW_SESSION="$(bw login --raw < /dev/tty)"
+                BW_SESSION="$(bw login --raw < /dev/tty)"
+                export BW_SESSION
                 ;;
             locked)
                 log "ERROR" "Bitwarden CLI is locked!"
                 echo "Please unlock bitwarden." >&2
-                export BW_SESSION="$(bw unlock --raw < /dev/tty)"
+                BW_SESSION="$(bw unlock --raw < /dev/tty)"
+                export BW_SESSION
                 ;;
             unlocked)
                 break
@@ -80,13 +82,13 @@ get_credentials() {
     
     if [[ $(get_bw_status) != "unlocked" ]]; then
         log "ERROR" "Bitwarden not unlocked!"
-        echo "Error: Bitward not unlocked!" >&2
+        echo "Error: Bitwarden not unlocked!" >&2
         exit 1
     fi
         
-    gitpass=$(bw list items --search ${host} | jq -r '.[] | select(.login.username == "'"${username}"'").fields[] | select(.name == "pat").value')
+    gitpass=$(bw list items --search "${host}" | jq -r '.[] | select(.login.username == "'"${username}"'").fields[] | select(.name == "pat").value')
     if [[ -z "${gitpass}" ]]; then
-        gitpass=$(bw list items --search ${host} | jq -r '.[] | select(.login.username == "'"${username}"'").login.password')
+        gitpass=$(bw list items --search "${host}" | jq -r '.[] | select(.login.username == "'"${username}"'").login.password')
     fi
     
     [[ -z "${gitpass}" ]] && { log "ERROR" "Could not find password in credential store"; exit 1; }
@@ -98,7 +100,7 @@ LOG_FILE=~/tmp/logs/git-credential-bw.log
 
 log_init
 
-if ! which bw &>/dev/null; then
+if ! command -v bw &>/dev/null; then
     log "ERROR" "Could not find Bitwarden CLI" >&2
     exit 1
 fi
